# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 10
  - name: Projects
    url: /#projs
    weight: 12
  # - name: Papers
  #   url: /#pub
  #   weight: 11
  # # - name: Background
  # #   url: /#detailed-ed
  # #   weight: 15
  - name: Mission
    url: /#vision
    weight: 13
  # - name: Talks
  #   url: /#talks
  #   weight: 14
  # - name: Hobbies
  #   url: /#hobbies
  #   weight: 16

  # - name: Courses
  #   url: courses/
  #   weight: 40
